FROM python:3.11

WORKDIR /app

ARG DOCKER_ENV_FILE

COPY ./apps/server/requirements.txt .
COPY ./.build-files/$DOCKER_ENV_FILE /app/.env
RUN pip install --no-cache-dir -r requirements.txt

COPY ./apps/server/ .