# Generated by Django 5.0.6 on 2024-06-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoonFileModel',
        ),
    ]
