# Generated by Django 5.0.6 on 2024-06-06 19:55

import s3_file_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoonFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worfklow_code', models.CharField(max_length=30)),
                ('file_type', models.CharField(max_length=10)),
                ('file_name', models.CharField(max_length=255)),
                ('location', models.DecimalField(decimal_places=0, max_digits=5)),
                ('unique_file_name', models.CharField(max_length=255)),
                ('temp_file_path', models.CharField(max_length=255)),
                ('file', s3_file_field.fields.S3FileField()),
            ],
        ),
    ]
