# Generated by Django 5.0.6 on 2024-06-10 18:15

import django.db.models.deletion
import s3_file_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_loonfilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoonTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('FAILED', 'Failed'), ('FINISHED', 'Finished')], default='PENDING', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='LoonFileModel',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.CreateModel(
            name='LoonUploadTask',
            fields=[
                ('loontask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.loontask')),
                ('workflow_code', models.CharField(choices=[('live_cyte', 'Live Cyte')], max_length=30)),
                ('file_type', models.CharField(choices=[('segmentations', 'Segmentations'), ('cell_images', 'Cell Images'), ('metadata', 'Metadata')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('location', models.DecimalField(decimal_places=0, max_digits=5)),
                ('unique_file_name', models.CharField(max_length=255)),
                ('temp_file_path', models.CharField(max_length=255)),
                ('blob', s3_file_field.fields.S3FileField()),
            ],
            bases=('api.loontask',),
        ),
    ]
