# Generated by Django 5.0.6 on 2024-06-10 20:01

import s3_file_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_loontask_delete_loonfilemodel_delete_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoonUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_code', models.CharField(choices=[('live_cyte', 'Live Cyte')], max_length=30)),
                ('file_type', models.CharField(choices=[('segmentations', 'Segmentations'), ('cell_images', 'Cell Images'), ('metadata', 'Metadata')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('location', models.DecimalField(decimal_places=0, max_digits=5)),
                ('unique_file_name', models.CharField(max_length=255)),
                ('temp_file_path', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('FAILED', 'Failed'), ('FINISHED', 'Finished')], default='PENDING', max_length=10)),
                ('blob', s3_file_field.fields.S3FileField()),
            ],
        ),
        migrations.RemoveField(
            model_name='loonuploadtask',
            name='loontask_ptr',
        ),
        migrations.DeleteModel(
            name='LoonTask',
        ),
        migrations.DeleteModel(
            name='LoonUploadTask',
        ),
    ]
