# Generated by Django 5.0.6 on 2024-06-11 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_experiment_remove_loonupload_status_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='segmentations_path',
            new_name='segmentations_folder',
        ),
        migrations.AlterField(
            model_name='location',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.experiment'),
        ),
    ]
