name: Deploy To Server
on:
  pull_request:
    branches: [dev]
    types: [closed]
jobs:
  curl-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make API request using curl
        run: |
          curl --location --request POST 'http://loonsw.sci.utah.edu:5421/deploy' \
            --header 'Authorization: ${{secrets.DEPLOYMENT_AUTH_TOKEN}}' \
            --max-time 10 \
            --fail \
            --show-error \
            --silent

      - name: Check for status code
        run: |
          if [ $? -ne 0 ]; then
            echo "Error: Failed to reach the server or no response. Exiting..."
            exit 1
          fi