name: Deploy To Server
on:
  pull_request:
    branches: [dev]
    types: [closed]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Hit API
        id: deployRequest
        uses: fjogeleit/http-request-action@v1.9.2
        with:
          url: 'https://loonsw.sci.utah.edu:8443/deploy/'
          method: 'GET'
          customHeaders: '{"Authorization": "${{secrets.DEPLOYMENT_AUTH_TOKEN}}"}'
        continue-on-error: true
      - name: Hit API CURL
        run: |
          curl --location 'https://loonsw.sci.utah.edu:8443/deploy' \
          --header 'Authorization: ${{secrets.DEPLOYMENT_AUTH_TOKEN}}'
        continue-on-error: true
      - name: Hit API CURL Healthcheck
        run: |
          curl --location 'https://loonsw.sci.utah.edu:8443/healthcheck' \
        continue-on-error: true


      # - name: Make API request using curl
      #   run: |
      #     curl --location --request POST 'http://loonsw.sci.utah.edu:5421/deploy' \
      #       --header 'Authorization: ${{secrets.DEPLOYMENT_AUTH_TOKEN}}' \
      #       --max-time 10 \
      #       --fail \
      #       --show-error \
      #       --silent

      # - name: Check for status code
      #   run: |
      #     if [ $? -ne 0 ]; then
      #       echo "Error: Failed to reach the server or no response. Exiting..."
      #       exit 1
      #     fi